### ISSUE TITLE
customize-cra

### ISSUE THREAD

**Issue by jamesmstone** [mzohaibqc/antd-theme-webpack-plugin#28]
Hi,
Firstly thank you, this looks like a really useful tool.
For `create-react-app` projects is it possible to use this with `customize-cra` instead of `react-app-rewired`, as `react-app-rewired` is now only "lightly" [maintained](https://github.com/timarney/react-app-rewired/issues/162#issuecomment-417872507).

**Comment by jamesmstone** [comment]
If so, it would be great to also update the `create-react-app` [example](https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/create-react-app)!

**Comment by jamesmstone** [comment]
Another alternative might be [`craco`](https://github.com/sharegate/craco)] or in particular: [`craco-antd`](https://github.com/DocSpring/craco-antd).

**Comment by mzohaibqc** [comment]
@jamesmstone Here are some hints, try this and if it works, update here so others can benefit from your learning

https://github.com/arackaf/customize-cra#addwebpackpluginplugin

```
const AntDesignThemePlugin = require('antd-theme-webpack-plugin');
const {
  override,
  addwebpackpluginplugin,
  addLessLoader
} = require("customize-cra");
const options = {
  stylesDir: path.join(__dirname, './src/less'),
  antDir: path.join(__dirname, './node_modules/antd'),
  varFile: path.join(__dirname, './src/less/vars.less'),
  mainLessFile: path.join(__dirname, './src/less/main.less'),
  themeVariables: [
    '@primary-color',
  ],
  indexFileName: 'index.html',
  generateOnce: false // generate color.less on each compilation
}

module.exports = override(
  addLessLoader({
    modifyVars: {
      '@primary-color': '#00375B'
    },
    javascriptEnabled: true
  }),
addwebpackpluginplugin(new AntDesignThemePlugin (options))
);
```

**Comment by Dppatra** [comment]
![Screenshot from 2019-07-18 17-16-27](https://user-images.githubusercontent.com/20948967/61455009-0c5f7000-a980-11e9-8e9a-575f029896f6.png)

This one is not working in  (customize-cra": "^0.4.1)

**Comment by mzohaibqc** [comment]
@Dppatra You should have seen the docs. You are not using the correct case for function name. It is `addWebpackPlugin` and not `addwebpackpluginplugin`

https://github.com/arackaf/customize-cra/blob/master/api.md#addwebpackpluginplugin

**Comment by buquan** [comment]
addwebpackpluginplugin is not a function@ @mzohaibqc

**Comment by mzohaibqc** [comment]
@buquan you should have seen the above comments. it's clearly saving it is `addWebpackPlugin` and not `addwebpackpluginplugin`. 

https://github.com/arackaf/customize-cra/blob/master/api.md#addwebpackpluginplugin

**Comment by buquan** [comment]
use addWebpackPlugin methods can't work , it  maintains 'Starting the development server...'

**Comment by mzohaibqc** [comment]
@buquan I've not tried this my self, do some changes, see the docs, you may get success

**Comment by mzohaibqc** [comment]
@jamesmstone @buquan Here is a demo using `customize-cra`
https://mzohaibqc.github.io/antd-theme-webpack-plugin/index.html

And here is code for this demo
https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/customize-cra
